title: Security In Action
description: Salesforce Admin Security Workshop
remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/sia.png"

url: https://joshbirk.github.io
baseurl: /securityinaction

permalink: pretty

aux_links:
  "View on GitHub":
    - "https://github.com/joshbirk/securityinaction"

# Footer
footer_content: "Salesforce Admin Security Workshop"

# Color scheme
color_scheme: light

# Nav
nav_sort: order

exclude:
  - siagoogledoc.md
  - source/
